### ISSUE TITLE
Cannot login in the login page, but forcing the same user in BIND_DN and BIND_PASSWORD works

### ISSUE THREAD

**Issue by gleitoncampos** [dnknth/ldap-ui#44] opened 2023-06-12 13:22 UTC
Hello!

As the title says, if I try to connect in the front (docker) with the example user "admin" and password "123456", the page just reloaded and back to login. But if I force the envs 'BIND_DN=cd-admin,dc=example,dc-com' and 'BIND_PASSWORD=123456' in docker command line, it works. 

Can you have any idea? Thank you!

**Comment by dnknth** [comment] 2023-06-12 13:53
Could there be a typo? `cd-admin,dc=example,dc-com` is syntactically wrong for a DN, and I doubt that it works. Did you mean `cn=admin,dc=example,dc=com`?

**Comment by gleitoncampos** [comment] 2023-06-12 18:54
> Could there be a typo? `cd-admin,dc=example,dc-com` is syntactically wrong for a DN, and I doubt that it works. Did you mean `cn=admin,dc=example,dc=com`?

Yes, sorry...  The correct was 'BIND_DN=cn=admin,dc=example,dc-com'

**Comment by gleitoncampos** [comment] 2023-06-12 19:10
> The last part `dc-com` does not look right either. Should it read: `dc=com`?

Damn... Right again, the correct one 'BIND_DN=cn=admin,dc=example,dc=com'
With this + bind_password forced in docker command, the front connect, but if I remove and try to connect in the front, nothing happens.

**Comment by dnknth** [comment] 2023-06-12 19:27
`LOGIN_ATTR` defaults to `uid`, but your admin user has a `cn` RDN. Therefore, you cannot log in as `admin` unless you also provide `-e LOGIN_ATTR=cn` on the Docker command line (or something equivalent in a compose file, or whatever you use). 

Technically, when you log in with Basic Auth and no `BIND_PATTERN` is given, a search is performed against the directory for a user whose `LOGIN_ATTR` matches the provided user name, in your case `uid=admin`. Obviously, this does not produce a result and therefore, the login fails.

Hope that helps.

**Comment by dnknth** [comment] 2023-06-13 17:25
Hello @gleitoncampos, did you solve it?

**Comment by dnknth** [comment] 2023-06-16 18:12
Closing this for lack of a response, feel free to re-open if the problem is not resolved

**Closed by dnknth** 2023-06-16 18:12 UTC
