### ISSUE TITLE
Internal Server Error: Socket not connected: Can't contact LDAP server

### ISSUE THREAD

**Issue by jared-bloomer** [dnknth/ldap-ui#43] opened 2023-03-08 16:27 UTC
I am attempting to use this to manage a 389DS installation. I know this has only been built for OpenLDAP, but from my experience the connection methods are the same across all LDAP servers. 

I have tried to connect on port 389 (ldap://) and I get the error `Internal Server Error: Socket not connected: Can't contact LDAP server`

When attempting to connect to port 636 (ldaps://) I get `Internal Server Error: error:0A000086:SSL routines::certificate verify failed (self-signed certificate in certificate chain): Can't contact LDAP server`

I am not sure how to establish the initial LDAP connection to my directory server. Also the documentation seems to be lacking as to what the environment variables are so I am not sure if there is anything I can do surround SSL Certs. 

I would like some advisement on what is needed to establish a successful connection.

**Comment by dnknth** [comment] 2023-06-16 19:55
Hi, @jared-bloomer, currently the app does not support LDAP over TLS. This should be added, and I will look into it.

**Comment by dnknth** [comment] 2023-06-18 21:21
Hello @jared-bloomer,

Correction: The app already did support LDAP over TLS, but neither self-signed certificates nor `STARTTLS`. Added this now, for self-signed certs you should set `INSECURE_TLS` either in an environment variable or in `.env`.

It works on my machine™️, please let me know whether you can now see the directory with the `leaps:` scheme.

**Comment by dnknth** [comment] 2023-06-19 18:35
Hello @jared-bloomer, 

Addition: When either `INSECURE_TLS` (in your case) or `USE_TLS` (for real certificates) are set, both `ldaps:` and `ldap:` schemes should work. in the latter case, the app will connect unencrypted on port 389 and then enable encryption with `STARTTLS` before logging in.

**Comment by dnknth** [comment] 2023-06-27 16:48
Closing due to lack of a response, feel free to re-open if the problem is not solved.

**Closed by dnknth** 2023-06-27 16:48 UTC
Labels: enhancement
